### ISSUE TITLE
Include golden_toolkits `loadAppFonts`

### ISSUE THREAD

**Issue by robiness** [passsy/spot#63]
Since `https://pub.dev/packages/golden_toolkit` is discontinued. And it's `loadAppFonts` is nearly always needed when taking a screenshot with spot. We should include 'loadAppFonts' into spot.

I'll create a PR. Feel free to assign me.  If any concerns or ideas let me know.

**Comment by passsy** [comment]
Released in [`0.15.0`](https://github.com/passsy/spot/releases/tag/v0.15.0)
